FROM python:3.11-slim
WORKDIR /usr/src/app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY pyproject.toml ./
RUN pip install --no-cache-dir --upgrade pip && \
    pip install .
COPY src ./src
COPY config ./config
EXPOSE 8001
CMD ["python", "src/time_profiler/chatbot_server.py"]
