version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: timeprofiler_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: timeprofiler_api
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m flask --app src.time_profiler.main:app run --host 0.0.0.0 --port 8000 --reload --debug
    volumes:
      - ./src:/usr/src/app/src
      - ./config:/usr/src/app/config
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: